id: 7672e65322b74d9786fab48397174db1
initial_creation_type: ocr
source_metadata:
  volumes:
    4c2a0f91272444ed974124f2c10dcb9a:
      base_file: v092.txt
      image_group_id: I1PD95938
      title: ''
      total_pages: 1484
      volume_number: 93
